vocabulary = [
    "ability", "absorb", "accept", "access", "accident", "account", "accurate", "achieve", "acid", "acquire", 
    "activate", "addition", "adventure", "advice", "affect", "afford", "afternoon", "against", "agency", "airplane", 
    "algorithm", "alive", "allow", "almost", "alphabet", "already", "amazing", "analyze", "ancient", "anger", 
    "announcement", "answer", "apartment", "appetite", "appreciate", "approve", "architecture", "argument", 
    "arrange", "article", "artist", "assemble", "assert", "assistance", "athlete", "atmosphere", "attempt", 
    "attractive", "auction", "audience", "authentic", "automatic", "average", "awesome", "background", "balance", 
    "barrier", "battery", "beautiful", "behavior", "believe", "benefit", "biology", "blanket", "boundary", 
    "bravery", "brightness", "broadcast", "butterfly", "calculate", "calendar", "campaign", "capability", 
    "captivate", "category", "celebrate", "challenge", "champion", "character", "charity", "chemistry", "childhood", 
    "choice", "chocolate", "circulate", "classic", "cleanse", "climate", "comfort", "comment", "communication", 
    "community", "compassion", "competition", "comprehensive", "concentrate", "concept", "conclusion", 
    "confident", "consider", "continuous", "contribute", "convenience", "conversation", "cooperate", 
    "courage", "creative", "criterion", "cucumber", "curiosity", "customize", "database", "dedicate", 
    "definition", "deliberate", "deliver", "demonstrate", "department", "dependent", "describe", 
    "design", "destination", "determine", "develop", "different", "dimension", "direction", "discover", 
    "discussion", "distribute", "diversity", "document", "dominate", "dramatic", "earnest", "economics", 
    "education", "effective", "effort", "efficient", "electricity", "elegant", "element", "eloquent", 
    "embrace", "emergency", "emphasize", "employee", "encourage", "endurance", "energetic", "engage", 
    "entertain", "enthusiastic", "environment", "equilibrium", "equipment", "essential", "establish", 
    "evaluate", "evidence", "evolve", "examine", "excellent", "exceptional", "experience", "experiment", 
    "expertise", "explore", "express", "extraordinary", "facility", "fantastic", "favorite", "feasible", 
    "federation", "fiction", "flexibility", "focus", "fragrance", "frequency", "fulfill", "fundamental", 
    "generate", "generation", "genuine", "geography", "gigantic", "global", "gorgeous", "government", 
    "gratitude", "guarantee", "harmony", "health", "heartfelt", "heaven", "heroic", "highlight", 
    "historical", "horizon", "humble", "humor", "hurricane", "hypothesis", "iconic", "identify", 
    "illuminate", "imagination", "immediate", "immigrate", "impact", "implement", "important", 
    "improve", "inclusive", "incredible", "individual", "industrious", "inevitable", "innovation", 
    "inspiration", "integrate", "intelligence", "intention", "interesting", "interpret", "intervention", 
    "introduce", "investigate", "invigorate", "irresistible", "isolate", "jubilant", "judicious", 
    "justify", "landscape", "legendary", "liberate", "limitless", "literature", "luxurious", "magnitude", 
    "maintain", "majestic", "manifest", "marvelous", "meaningful", "mediate", "memorable", "metamorphosis", 
    "meticulous", "momentum", "motivate", "multifaceted", "mysterious", "navigate", "necessary", "negotiate", 
    "network", "nurture", "obligation", "observe", "occasion", "operate", "opportunity", "optimistic", 
    "organization", "originate", "outstanding", "overcome", "paradise", "participate", "passionate", 
    "perception", "performance", "persevere", "perspective", "pharmaceutical", "phenomenal", "philanthropy", 
    "plentiful", "pioneer", "pleasant", "plethora", "potential", "pragmatic", "precious", "preference", 
    "preparation", "preserve", "prevail", "primary", "priority", "problem", "proclaim", "prodigious", 
    "productive", "proficient", "progress", "prominent", "prosper", "protect", "proven", "psychology", 
    "pursue", "quantity", "quintessential", "radiance", "realize", "reassure", "recognize", "recommend", 
    "recovery", "reference", "reflect", "rejoice", "relaxation", "reliable", "remarkable", "renewal", 
    "renovate", "repair", "replace", "representation", "replicate", "request", "resilient", "resolve", 
    "resourceful", "respect", "responsible", "restore", "result", "revitalize", "revolutionary", "rhapsody", 
    "satisfaction", "schedule", "science", "scrutinize", "sensation", "sensitive", "significant", 
    "simplicity", "sophisticated", "special", "spectacular", "spontaneous", "stability", "startling", 
    "strategy", "strength", "structure", "stupendous", "succeed", "success", "sufficient", "suggestion", 
    "superb", "support", "surpass", "surround", "sustainable", "symbolize", "synergy", "synthesize", 
    "system", "technology", "tenacious", "terminate", "testimonial", "theater", "theory", "therapeutic", 
    "transform", "transition", "triumph", "ultimate", "understand", "undoubtedly", "unexpected", 
    "unify", "unique", "universal", "unleash", "unprecedented", "uplift", "utilize", "validate", 
    "value", "vast", "venture", "versatile", "vibrant", "victory", "vigorous", "vision", "vitality", 
    "vivid", "volunteer", "vulnerable", "wander", "warmth", "waterfall", "wealth", "welcome", "wholesome", 
    "wonderful", "workshop", "worthwhile", "yearn", "yield", "zeal", "python", "java", "hope", "Hello", "Hi", "Welcome", "How"
]
